- name: "unarchive | https://get.helm.sh/helm-{{ ansible_role_helm_version }}-linux-amd64.tar.gz"
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-{{ ansible_role_helm_version }}-linux-amd64.tar.gz
    dest: /tmp/test
    remote_src: yes
