- name: "stat | /opt/ansible-role-helm/{{ ansible_role_helm_version }}"
  ansible.builtin.stat:
    path: "/opt/ansible-role-helm/{{ ansible_role_helm_version }}"
  register: _stat

- name: debug
  debug:        
    msg: "{{ _stat }}"

- name: "directory | /opt/ansible-role-helm/{{ ansible_role_helm_version }}"
  ansible.builtin.file:
    path: "/opt/ansible-role-helm/{{ ansible_role_helm_version }}"
    state: directory
    recurse: true

- name: "unarchive | https://get.helm.sh/helm-{{ ansible_role_helm_version }}-linux-amd64.tar.gz"
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-{{ ansible_role_helm_version }}-linux-amd64.tar.gz
    dest: /tmp/test
    remote_src: yes
